<a href="https://colab.research.google.com/github/ai-with-sam/LearnPandas/blob/main/Pandas_PivotTable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

data = {
    'order_id': ['O1','O2','O3','O4','O5','O6','O7','O8','O9','O10','O11','O12'],
    'city': ['Mumbai','Delhi','Mumbai','Bangalore','Delhi','Mumbai','Delhi',
             'Bangalore','Mumbai','Delhi','Bangalore','Mumbai'],
    'category': ['Tech','Furniture','Tech','Office','Tech','Furniture','Office',
                 'Tech','Office','Furniture','Furniture','Tech'],
    'sales': [25000, 8000, 15000, 3000, 32000,np.nan , 5500, 18000, 4200, 9800, 7600, 21000],
    'profit': [5000, -500, 3200, 800, 8000, 1200, 600, 4000, -300, 1900, 1100, 5200],
    'order_date': pd.to_datetime(['2025-01-05','2025-01-08','2025-02-10','2025-02-12',
                                   '2025-02-15','2025-03-01','2025-03-05','2025-03-10',
                                   '2025-03-15','2025-04-01','2025-04-05','2025-04-10'])
}
df = pd.DataFrame(data)
df

   order_id       city   category    sales  profit order_date
0        O1     Mumbai       Tech  25000.0    5000 2025-01-05
1        O2      Delhi  Furniture   8000.0    -500 2025-01-08
2        O3     Mumbai       Tech  15000.0    3200 2025-02-10
3        O4  Bangalore     Office   3000.0     800 2025-02-12
4        O5      Delhi       Tech  32000.0    8000 2025-02-15
5        O6     Mumbai  Furniture      NaN    1200 2025-03-01
6        O7      Delhi     Office   5500.0     600 2025-03-05
7        O8  Bangalore       Tech  18000.0    4000 2025-03-10
8        O9     Mumbai     Office   4200.0    -300 2025-03-15
9       O10      Delhi  Furniture   9800.0    1900 2025-04-01
10      O11  Bangalore  Furniture   7600.0    1100 2025-04-05
11      O12     Mumbai       Tech  21000.0    5200 2025-04-10

In [4]:
df.pivot_table(
    index='city',
    values='sales',
    columns='category',
    aggfunc='sum'
    )

category   Furniture  Office     Tech
city
Bangalore     7600.0  3000.0  18000.0
Delhi        17800.0  5500.0  32000.0
Mumbai           0.0  4200.0  61000.0

groupby() vs pivot_table()

groupby()-Used for analysis.
pivot_table()-Used for reports.

In [9]:
# Pivot Table with Multiple Values

df.pivot_table(
    index='city',
    values=['sales','profit'],
    columns='category',
    aggfunc=['sum','mean'],
    fill_value=0 # Replace Nan values to 0
    )

                sum                                               mean         \
             profit                   sales                     profit
category  Furniture Office   Tech Furniture  Office     Tech Furniture Office
city
Bangalore      1100    800   4000    7600.0  3000.0  18000.0    1100.0  800.0
Delhi          1400    600   8000   17800.0  5500.0  32000.0     700.0  600.0
Mumbai         1200   -300  13400       0.0  4200.0  61000.0    1200.0 -300.0


                           sales
category          Tech Furniture  Office          Tech
city
Bangalore  4000.000000    7600.0  3000.0  18000.000000
Delhi      8000.000000    8900.0  5500.0  32000.000000
Mumbai     4466.666667       0.0  4200.0  20333.333333

Margins (Grand Totals)
-Add totals to the report.

In [11]:
df.pivot_table(
    index='city',
    values='sales',
    columns='category',
    aggfunc='sum',
    margins=True
    )

category   Furniture   Office      Tech       All
city
Bangalore     7600.0   3000.0   18000.0   28600.0
Delhi        17800.0   5500.0   32000.0   55300.0
Mumbai           0.0   4200.0   61000.0   65200.0
All          25400.0  12700.0  111000.0  149100.0

In [12]:
df.pivot_table(
    index='city',
    values='sales',
    columns='category',
    aggfunc=['sum','mean'],
    margins=True
    )

                sum                                      mean               \
category  Furniture   Office      Tech       All    Furniture       Office
city
Bangalore    7600.0   3000.0   18000.0   28600.0  7600.000000  3000.000000
Delhi       17800.0   5500.0   32000.0   55300.0  8900.000000  5500.000000
Mumbai          0.0   4200.0   61000.0   65200.0          NaN  4200.000000
All         25400.0  12700.0  111000.0  149100.0  8466.666667  4233.333333


category           Tech           All
city
Bangalore  18000.000000   9533.333333
Delhi      32000.000000  13825.000000
Mumbai     20333.333333  16300.000000
All        22200.000000  13554.545455

In [13]:
df.pivot_table(
    index='city',
    values=['sales','profit'],
    columns='category',
    aggfunc='sum',
    margins=True
    )

             profit                             sales                     \
category  Furniture  Office     Tech    All Furniture   Office      Tech
city
Bangalore    1100.0   800.0   4000.0   5900    7600.0   3000.0   18000.0
Delhi        1400.0   600.0   8000.0  10000   17800.0   5500.0   32000.0
Mumbai       1200.0  -300.0  13400.0  13100       0.0   4200.0   61000.0
All          2500.0  1100.0  25400.0  29000   25400.0  12700.0  111000.0


category        All
city
Bangalore   28600.0
Delhi       55300.0
Mumbai      65200.0
All        149100.0

In [17]:
df.pivot_table(
    index='city',
    values=['sales','profit'],
    columns='category',
    aggfunc='sum',
    margins=True,
    margins_name='Total_sales' # Adds label to Total values
    )

               profit                                  sales           \
category    Furniture  Office     Tech Total_sales Furniture   Office
city
Bangalore      1100.0   800.0   4000.0        5900    7600.0   3000.0
Delhi          1400.0   600.0   8000.0       10000   17800.0   5500.0
Mumbai         1200.0  -300.0  13400.0       13100       0.0   4200.0
Total_sales    2500.0  1100.0  25400.0       29000   25400.0  12700.0


category         Tech Total_sales
city
Bangalore     18000.0     28600.0
Delhi         32000.0     55300.0
Mumbai        61000.0     65200.0
Total_sales  111000.0    149100.0

In [29]:
pivotlearn = df.pivot_table(
    index='city',
    values=['sales','profit'],
    columns='category',
    aggfunc='sum',
    margins=False, # Removes the summed up column
    margins_name='Total_sales' # Adds label to Total values
    )
pivotlearn

             profit                   sales
category  Furniture Office   Tech Furniture  Office     Tech
city
Bangalore      1100    800   4000    7600.0  3000.0  18000.0
Delhi          1400    600   8000   17800.0  5500.0  32000.0
Mumbai         1200   -300  13400       0.0  4200.0  61000.0

In [30]:
pivotlearn.loc['Average'] = pivotlearn.mean() #Calculates the mean of each column
                                              # Adds a new row named "Average" to the DataFrame
pivotlearn

                profit                                   sales               \
category     Furniture      Office          Tech     Furniture       Office
city
Bangalore  1100.000000  800.000000   4000.000000   7600.000000  3000.000000
Delhi      1400.000000  600.000000   8000.000000  17800.000000  5500.000000
Mumbai     1200.000000 -300.000000  13400.000000      0.000000  4200.000000
Average    1233.333333  366.666667   8466.666667   8466.666667  4233.333333


category      Tech
city
Bangalore  18000.0
Delhi      32000.0
Mumbai     61000.0
Average    37000.0

In [31]:
pivotlearn['Average'] = pivotlearn.mean(axis=1)
# This selects (or creates) a column named "Average".
#Since it doesn't exist, pandas creates it.

pivotlearn

                profit                                   sales               \
category     Furniture      Office          Tech     Furniture       Office
city
Bangalore  1100.000000  800.000000   4000.000000   7600.000000  3000.000000
Delhi      1400.000000  600.000000   8000.000000  17800.000000  5500.000000
Mumbai     1200.000000 -300.000000  13400.000000      0.000000  4200.000000
Average    1233.333333  366.666667   8466.666667   8466.666667  4233.333333

                         Average
category      Tech
city
Bangalore  18000.0   5750.000000
Delhi      32000.0  10883.333333
Mumbai     61000.0  13250.000000
Average    37000.0   9961.111111

In [34]:
print("Before flattening:")
print(pivotlearn.columns.tolist())

Before flattening:
[('profit', 'Furniture'), ('profit', 'Office'), ('profit', 'Tech'), ('sales', 'Furniture'), ('sales', 'Office'), ('sales', 'Tech'), ('Average', '')]

In [41]:
flat_pivot = pivotlearn.copy()

for col in flat_pivot:
  print('_'.join(col))
flat_pivot

profit_Furniture
profit_Office
profit_Tech
sales_Furniture
sales_Office
sales_Tech
Average_

                profit                                   sales               \
category     Furniture      Office          Tech     Furniture       Office
city
Bangalore  1100.000000  800.000000   4000.000000   7600.000000  3000.000000
Delhi      1400.000000  600.000000   8000.000000  17800.000000  5500.000000
Mumbai     1200.000000 -300.000000  13400.000000      0.000000  4200.000000
Average    1233.333333  366.666667   8466.666667   8466.666667  4233.333333

                         Average
category      Tech
city
Bangalore  18000.0   5750.000000
Delhi      32000.0  10883.333333
Mumbai     61000.0  13250.000000
Average    37000.0   9961.111111

In [39]:
flat_pivot.columns = ['_'.join(col).strip() for col in flat_pivot.columns.values] #List comprehension
# normal for loop
# new_columns = []

# for col in flat_pivot.columns.values:
#    new_col = '_'.join(col).strip()
#    new_columns.append(new_col)

# flat_pivot.columns = new_columns

flat_pivot

,profit_Furniture,profit_Office,profit_Tech,sales_Furniture,sales_Office,sales_Tech,Average_
city,,,,,,,
Bangalore,1100.000000,800.000000,4000.000000,7600.000000,3000.000000,18000.0,5750.000000
Delhi,1400.000000,600.000000,8000.000000,17800.000000,5500.000000,32000.0,10883.333333
Mumbai,1200.000000,-300.000000,13400.000000,0.000000,4200.000000,61000.0,13250.000000
Average,1233.333333,366.666667,8466.666667,8466.666667,4233.333333,37000.0,9961.111111

In [44]:
x=[1,2,3,4,5]
y=[]

for value in x:
    y.append(value**2)
print(y)

[1, 4, 9, 16, 25]

In [45]:
x=[1,2,3,4,5]
y=[]
y = [value**2 for value in x]
y

[1, 4, 9, 16, 25]