<a href="https://colab.research.google.com/github/ai-with-sam/LearnPandas/blob/main/PandasBasics1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data = pd.Series([23,45,78],index=['CBE', 'BLR', 'CHN'])
print(data)

CBE    23
BLR    45
CHN    78
dtype: int64

In [ ]:
d = {
    "Name":['Sam', 'Ronaldo', 'Raina'],
    "Age": [27, 40, 35],
    "Sports": ['Tennis', 'Football', 'Cricket']
}

df = pd.DataFrame(d)
print(df)

      Name  Age    Sports
0      Sam   27    Tennis
1  Ronaldo   40  Football
2    Raina   35   Cricket

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Sports  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [ ]:
df.describe()

             Age
count   3.000000
mean   34.000000
std     6.557439
min    27.000000
25%    31.000000
50%    35.000000
75%    37.500000
max    40.000000

In [ ]:
df.head(1)

  Name  Age  Sports
0  Sam   27  Tennis

In [ ]:
df.tail(2)

      Name  Age    Sports
1  Ronaldo   40  Football
2    Raina   35   Cricket

#df["col"]	Returns Series
#df[["col"]]	Returns DataFrame

In [ ]:
df['Age'] #Returns Series

0    27
1    40
2    35
Name: Age, dtype: int64

In [ ]:
df[['Age','Sports']]

   Age    Sports
0   27    Tennis
1   40  Football
2   35   Cricket

In [ ]:
df1=df[df['Age']>30]
df1

      Name  Age    Sports
1  Ronaldo   40  Football
2    Raina   35   Cricket

In [ ]:
def fib(n):
  if(n==0):
    return 0
  elif(n==1):
    return 1
  else:
    return fib(n-1)+fib(n-2)
terms = int(input("Enter the number of terms: "))
for i in range(terms):
  print(fib(i), end=" ")

Enter the number of terms: 5
0 1 1 2 3